# version: '3.8'

services:

  postgres_tel:
    image: postgres:16
    container_name: postgres_telecom
    ports:
      - "${post_port_externe}:5432"
    env_file:
      - ../.env
    environment:
          POSTGRES_USER: ${post_user}
          POSTGRES_PASSWORD: ${post_pwd}
          POSTGRES_DB: ${post_db_name}
    volumes:
      - ./DataWarehouse_data:/var/lib/postgresql/data 
      - ./data:/tmp:rw
    networks:
      - adao_telecom 

  
  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt_telecom
    depends_on:
      - postgres_tel
    volumes:
      - ./dbt:/usr/app
    working_dir: /usr/app
    tty: true
    stdin_open: true
    networks:
      - adao_telecom




    